services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\Reports\:
    resource: '../Classes/*'
    # Tasks require EXT:scheduler to be installed, ignore for now.
    exclude: '../Classes/Task'

  TYPO3\CMS\Reports\Controller\ReportController:
    tags: ['backend.controller']

  TYPO3\CMS\Reports\Report\WarningsForAboutModule:
    tags:
      - name: event.listener
        identifier: 'typo3-reports/warnings'
